import type { Locale } from '@/lib/i18n/locale';

const productEditorPreviewMessages: Record<Locale, Record<string, string>> = {
  zh: {
    'common.requestQuote': '获取报价',
    'common.viewAllProducts': '查看全部产品',
    'nav.home': '首页',
    'page.products.title': '产品中心',
    'product.detail.applications': '适用场景',
    'product.detail.care': '洗护与维护',
    'product.detail.careTag': '维护',
    'product.detail.carouselNext': '下一张图片',
    'product.detail.carouselPrevious': '上一张图片',
    'product.detail.category': '类别',
    'product.detail.color': '颜色',
    'product.detail.evidenceTag': '资料',
    'product.detail.evidenceTitle': '资料与认证状态',
    'product.detail.faq': '常见问题',
    'product.detail.faqTag': 'FAQ',
    'product.detail.features': '产品特点',
    'product.detail.gallery': '产品图库',
    'product.detail.introTag': '介绍',
    'product.detail.materials': '材料',
    'product.detail.model': '型号',
    'product.detail.navTitle': '详情目录',
    'product.detail.overview': '产品概述',
    'product.detail.productIntro': '商品介绍',
    'product.detail.scenarioTag': '应用',
    'product.detail.sellingPoints': '核心卖点',
    'product.detail.sellingPointsTag': '核心优势',
    'product.detail.sizeGuide': '尺码对应表',
    'product.detail.sizeGuideTag': '尺码',
    'product.detail.sizeRange': '尺码',
    'product.detail.specTag': '技术参数',
    'product.detail.specifications': '参数规格',
    'product.detail.standard': '执行标准',
    'product.detail.structure': '结构',
    'product.detail.visualTag': '图册',
    'product.detail.visualTitle': '场景图、建模图与模特上身图',
  },
  en: {
    'common.requestQuote': 'Request Quote',
    'common.viewAllProducts': 'View All Products',
    'nav.home': 'Home',
    'page.products.title': 'Products Center',
    'product.detail.applications': 'Applications',
    'product.detail.care': 'Care & Maintenance',
    'product.detail.careTag': 'Care',
    'product.detail.carouselNext': 'Next image',
    'product.detail.carouselPrevious': 'Previous image',
    'product.detail.category': 'Category',
    'product.detail.color': 'Color',
    'product.detail.evidenceTag': 'Documents',
    'product.detail.evidenceTitle': 'Materials & Certification Status',
    'product.detail.faq': 'FAQ',
    'product.detail.faqTag': 'FAQ',
    'product.detail.features': 'Key Features',
    'product.detail.gallery': 'Product gallery',
    'product.detail.introTag': 'Profile',
    'product.detail.materials': 'Materials',
    'product.detail.model': 'Model',
    'product.detail.navTitle': 'Detail sections',
    'product.detail.overview': 'Overview',
    'product.detail.productIntro': 'Product Introduction',
    'product.detail.scenarioTag': 'Use Cases',
    'product.detail.sellingPoints': 'Core Selling Points',
    'product.detail.sellingPointsTag': 'Highlights',
    'product.detail.sizeGuide': 'Size Guide',
    'product.detail.sizeGuideTag': 'Sizing',
    'product.detail.sizeRange': 'Size range',
    'product.detail.specTag': 'Technical',
    'product.detail.specifications': 'Parameters & Specifications',
    'product.detail.standard': 'Standard',
    'product.detail.structure': 'Structure',
    'product.detail.visualTag': 'Gallery',
    'product.detail.visualTitle': 'Scenes, Modeling Views & Model Wearing Views',
  },
  ru: {
    'common.requestQuote': 'Запросить цену',
    'common.viewAllProducts': 'Вся продукция',
    'nav.home': 'Главная',
    'page.products.title': 'Центр продукции',
    'product.detail.applications': 'Применение',
    'product.detail.care': 'Уход и обслуживание',
    'product.detail.careTag': 'Уход',
    'product.detail.carouselNext': 'Следующее изображение',
    'product.detail.carouselPrevious': 'Предыдущее изображение',
    'product.detail.category': 'Категория',
    'product.detail.color': 'Цвет',
    'product.detail.evidenceTag': 'Документы',
    'product.detail.evidenceTitle': 'Материалы и статус сертификации',
    'product.detail.faq': 'Частые вопросы',
    'product.detail.faqTag': 'FAQ',
    'product.detail.features': 'Ключевые особенности',
    'product.detail.gallery': 'Галерея продукта',
    'product.detail.introTag': 'Описание',
    'product.detail.materials': 'Материалы',
    'product.detail.model': 'Модель',
    'product.detail.navTitle': 'Разделы',
    'product.detail.overview': 'Обзор',
    'product.detail.productIntro': 'Описание продукта',
    'product.detail.scenarioTag': 'Применение',
    'product.detail.sellingPoints': 'Ключевые преимущества',
    'product.detail.sellingPointsTag': 'Преимущества',
    'product.detail.sizeGuide': 'Таблица размеров',
    'product.detail.sizeGuideTag': 'Размеры',
    'product.detail.sizeRange': 'Размеры',
    'product.detail.specTag': 'Технические данные',
    'product.detail.specifications': 'Параметры и спецификации',
    'product.detail.standard': 'Стандарт',
    'product.detail.structure': 'Структура',
    'product.detail.visualTag': 'Галерея',
    'product.detail.visualTitle': 'Сцены, модельные виды и фото на модели',
  },
};

export function productEditorPreviewLabel(locale: Locale, key: string) {
  return productEditorPreviewMessages[locale][key] ?? productEditorPreviewMessages.zh[key] ?? key;
}
