/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    'form-submissions': FormSubmission;
    'product-groups': ProductGroup;
    'product-categories': ProductCategory;
    products: Product;
    solutions: Solution;
    news: News;
    pages: Page;
    faqs: Faq;
    media: Media;
    'search-logs': SearchLog;
    users: User;
    roles: Role;
    'audit-logs': AuditLog;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {
    navigation: Navigation;
    'site-settings': SiteSetting;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  name: string;
  country?: string | null;
  company?: string | null;
  position?: string | null;
  phone?: string | null;
  email?: string | null;
  inquiryType: 'franchise' | 'message';
  message: string;
  productRef?: (number | null) | Product;
  status: 'new' | 'processing' | 'replied' | 'closed';
  assignedTo?: string | null;
  notes?:
    | {
        at: string;
        user?: string | null;
        text: string;
        id?: string | null;
      }[]
    | null;
  sourceUrl?: string | null;
  sourceLocale?: ('zh' | 'en' | 'ru') | null;
  ip?: string | null;
  userAgent?: string | null;
  consentAcceptedAt: string;
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  productId: string;
  sku?: string | null;
  model?: string | null;
  name: string;
  slug: string;
  productGroup: number | ProductGroup;
  category?: (number | null) | ProductCategory;
  industries?:
    | ('firefighting' | 'power' | 'petrochemical' | 'steel' | 'medical' | 'welding' | 'defense' | 'emergency-rescue')[]
    | null;
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  standards?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  materials?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  applications?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  features?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  specifications?:
    | {
        label?: string | null;
        value?: string | null;
        group?: string | null;
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  sizeRange?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  images?:
    | {
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  video?: number | Media | null;
  relatedProducts?: (number | Product)[] | null;
  faqs?: (number | Faq)[] | null;
  isFeatured?: boolean | null;
  displayOrder?: number | null;
  publishedAt?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?: string | null;
    ogImage?: number | Media | null;
    noindex?: boolean | null;
    canonical?: string | null;
  };
  certifications?:
    | {
        name: string;
        issuer?: string | null;
        certNumber?: string | null;
        status?: ('valid' | 'expired' | 'pending' | 'not-applicable') | null;
        validUntil?: string | null;
        attachment?: number | Media | null;
        id?: string | null;
      }[]
    | null;
  sizeGuide?: {
    title?: string | null;
    cornerLabel?: string | null;
    columns?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    rows?:
      | {
          label: string;
          values?:
            | {
                value: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  qualityEvidence?:
    | {
        type: 'certificate' | 'test-report' | 'inspection' | 'case-study' | 'other';
        status?: string | null;
        title: string;
        description?: string | null;
        attachment?: number | Media | null;
        id?: string | null;
      }[]
    | null;
  visualGroups?:
    | {
        variant?: ('gallery' | 'scene' | 'modeling' | 'model' | 'detail' | 'certificate' | 'comparison') | null;
        title?: string | null;
        description?: string | null;
        images?:
          | {
              file: number | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  careInstructions?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  sellingPoints?:
    | {
        title: string;
        text?: string | null;
        icon?: number | Media | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-groups".
 */
export interface ProductGroup {
  id: number;
  groupId: string;
  slug: string;
  name: string;
  description?: string | null;
  showOnFrontend?: boolean | null;
  order?: number | null;
  cover?: number | Media | null;
  icon?: number | Media | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?: string | null;
    ogImage?: number | Media | null;
    noindex?: boolean | null;
    canonical?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  credit?: string | null;
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  folder?: ('brand' | 'products' | 'news' | 'icons' | 'video' | 'pdf' | 'misc') | null;
  usageCount?: number | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    mobile?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories".
 */
export interface ProductCategory {
  id: number;
  categoryId: string;
  slug: string;
  name: string;
  description?: string | null;
  productGroup?: (number | null) | ProductGroup;
  group?: ('fire-rescue' | 'electrical-protection' | 'thermal-welding' | 'chemical-medical' | 'water-rescue') | null;
  parent?: (number | null) | ProductCategory;
  cover?: number | Media | null;
  icon?: number | Media | null;
  order?: number | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?: string | null;
    ogImage?: number | Media | null;
    noindex?: boolean | null;
    canonical?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  scope: 'global' | 'page' | 'product' | 'news';
  pageRef?: (number | null) | Page;
  productRef?: (number | null) | Product;
  newsRef?: (number | null) | News;
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  isPublished: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  pageKey:
    | 'home'
    | 'about'
    | 'products-index'
    | 'solutions'
    | 'news-index'
    | 'franchise'
    | 'contact'
    | 'privacy'
    | 'cookies'
    | 'terms';
  title: string;
  slug?: string | null;
  hero?: {
    enabled?: boolean | null;
    variant?: ('video-bg' | 'image-bg' | 'carousel' | 'plain') | null;
    title?: string | null;
    subtitle?: string | null;
    backgroundImage?: number | Media | null;
    backgroundVideo?: number | Media | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  blocks?:
    | (
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
        | {
            layout?: ('media-left' | 'media-right') | null;
            media?: number | Media | null;
            title?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaText';
          }
        | {
            title?: string | null;
            category?: (number | null) | ProductCategory;
            products?: (number | Product)[] | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'productShowcase';
          }
        | {
            title?: string | null;
            category?: ('news' | 'event' | 'announcement' | 'exhibition') | null;
            news?: (number | News)[] | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsList';
          }
        | FaqContentBlock
        | {
            title?: string | null;
            description?: string | null;
            primaryLabel?: string | null;
            primaryHref?: string | null;
            secondaryLabel?: string | null;
            secondaryHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            items?:
              | {
                  value: string;
                  label: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            title?: string | null;
            showForm?: boolean | null;
            showMap?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contact';
          }
      )[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?: string | null;
    ogImage?: number | Media | null;
    noindex?: boolean | null;
    canonical?: string | null;
  };
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  excerpt?: string | null;
  author?: string | null;
  cover: number | Media;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category: 'news' | 'event' | 'announcement' | 'exhibition';
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  publishedAt: string;
  isFeatured?: boolean | null;
  relatedNews?: (number | News)[] | null;
  relatedProducts?: (number | Product)[] | null;
  slug: string;
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?: string | null;
    ogImage?: number | Media | null;
    noindex?: boolean | null;
    canonical?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqContentBlock".
 */
export interface FaqContentBlock {
  title?: string | null;
  faqs?: (number | Faq)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions".
 */
export interface Solution {
  id: number;
  solutionId: string;
  title: string;
  summary?: string | null;
  cover?: number | Media | null;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  features?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  productTags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  relatedProductGroups?: (number | ProductGroup)[] | null;
  relatedCategories?: (number | ProductCategory)[] | null;
  relatedProducts?: (number | Product)[] | null;
  isFeatured?: boolean | null;
  order?: number | null;
  publishedAt?: string | null;
  slug: string;
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?: string | null;
    ogImage?: number | Media | null;
    noindex?: boolean | null;
    canonical?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search-logs".
 */
export interface SearchLog {
  id: number;
  eventType: 'search' | 'result-click';
  query: string;
  locale: 'zh' | 'en' | 'ru';
  hits: number;
  resultId?: string | null;
  resultTitle?: string | null;
  resultType?: ('product' | 'news' | 'page' | 'faq') | null;
  resultUrl?: string | null;
  userId?: string | null;
  ip: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: number | Role;
  lastLoginAt?: string | null;
  twoFactorEnabled?: boolean | null;
  twoFactorSecret?: string | null;
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  permissions:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  user?: (number | null) | User;
  userEmail: string;
  action:
    | 'login'
    | 'logout'
    | 'login_failed'
    | 'create'
    | 'update'
    | 'delete'
    | 'restore'
    | 'publish'
    | 'unpublish'
    | 'upload'
    | 'media-delete'
    | 'form-submitted'
    | 'role-change'
    | 'permission-grant'
    | 'permission-revoke'
    | 'config-change';
  collection?: string | null;
  documentId?: string | null;
  documentSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  ip?: string | null;
  userAgent?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  mainNav?:
    | {
        label: string;
        href: string;
        icon?: number | Media | null;
        target?: ('_self' | '_blank') | null;
        children?:
          | {
              label: string;
              href: string;
              icon?: number | Media | null;
              target?: ('_self' | '_blank') | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footerNav?:
    | {
        heading?: string | null;
        items?:
          | {
              label: string;
              href: string;
              icon?: number | Media | null;
              target?: ('_self' | '_blank') | null;
              children?:
                | {
                    label: string;
                    href: string;
                    icon?: number | Media | null;
                    target?: ('_self' | '_blank') | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  mobileNav?:
    | {
        label: string;
        href: string;
        icon?: number | Media | null;
        target?: ('_self' | '_blank') | null;
        children?:
          | {
              label: string;
              href: string;
              icon?: number | Media | null;
              target?: ('_self' | '_blank') | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  contact?: {
    phone?: string | null;
    email?: string | null;
    address?: string | null;
  };
  coordinates?: {
    lat?: number | null;
    lng?: number | null;
    zoom?: number | null;
  };
  socials?:
    | {
        platform: 'wechat' | 'weibo' | 'linkedin' | 'youtube' | 'facebook' | 'x' | 'other';
        url: string;
        icon?: number | Media | null;
        id?: string | null;
      }[]
    | null;
  siteName: string;
  tagline?: string | null;
  logo: {
    light: number | Media;
    dark: number | Media;
  };
  favicon: number | Media;
  appleTouchIcon?: number | Media | null;
  themeColor: string;
  defaultSeo?: {
    title?: string | null;
    description?: string | null;
    keywords?: string | null;
    ogImage?: number | Media | null;
    noindex?: boolean | null;
    canonical?: string | null;
  };
  mapServiceByLocale?:
    | {
        locale: 'zh' | 'en' | 'ru';
        service: 'amap' | 'google';
        id?: string | null;
      }[]
    | null;
  cookieConsent?: {
    enabled?: boolean | null;
    title?: string | null;
    description?: string | null;
    acceptLabel?: string | null;
    rejectLabel?: string | null;
    essentialOnlyLabel?: string | null;
  };
  analytics?: {
    enabled?: boolean | null;
    umamiWebsiteId?: string | null;
  };
  icp: string;
  publicSecurityRecord?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
