/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'form-submissions': FormSubmission;
    'product-groups': ProductGroup;
    'product-categories': ProductCategory;
    products: Product;
    solutions: Solution;
    news: News;
    pages: Page;
    faqs: Faq;
    media: Media;
    'search-logs': SearchLog;
    users: User;
    roles: Role;
    'audit-logs': AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'product-groups': ProductGroupsSelect<false> | ProductGroupsSelect<true>;
    'product-categories': ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    solutions: SolutionsSelect<false> | SolutionsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'search-logs': SearchLogsSelect<false> | SearchLogsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents':
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('zh' | 'en' | 'ru')
    | ('zh' | 'en' | 'ru')[];
  globals: {
    navigation: Navigation;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'zh' | 'en' | 'ru';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  name: string;
  country?: string | null;
  company?: string | null;
  position?: string | null;
  phone: string;
  email: string;
  inquiryType: 'franchise' | 'message';
  message: string;
  productRef?: (number | null) | Product;
  status: 'new' | 'processing' | 'replied' | 'closed';
  /**
   * Enter the offline follow-up owner’s name directly.
   */
  assignedTo?: string | null;
  notes?:
    | {
        at: string;
        /**
         * Enter the follow-up owner’s name directly.
         */
        user?: string | null;
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Recorded automatically by the submission page.
   */
  sourceUrl?: string | null;
  sourceLocale?: ('zh' | 'en' | 'ru') | null;
  ip?: string | null;
  userAgent?: string | null;
  consentAcceptedAt: string;
  /**
   * Written only by the system during soft delete. Empty means the record is active.
   */
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Maintain storefront product cards and detail pages. Product numbers and names identify products and build links; a real main image is required before publishing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Stable ID used in storefront detail-page links. Avoid changing it after creation.
   */
  productId: string;
  sku?: string | null;
  /**
   * Optional. Shown beside the storefront detail hero image and in the specifications area.
   */
  model?: string | null;
  name: string;
  /**
   * Generated from productId by default. P2.S4 adds full pinyin and uniqueness handling.
   */
  slug: string;
  /**
   * Required. Choose the product group first when creating a product; the storefront Product Center will place the product under that group.
   */
  productGroup: number | ProductGroup;
  images?:
    | {
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown as the summary beside the hero image and used as the overview in the Product Introduction section.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  standards?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  sizeRange?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  materials?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Leave empty when there are no features. The storefront only shows filled items.
   */
  features?:
    | {
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * P3+ extended field: marketing selling points.
   */
  sellingPoints?:
    | {
        title?: string | null;
        text?: string | null;
        icon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Use the legacy detail-page specification table. You can add model, standards, color, size, material, category, structure, etc. Do not add empty items; the storefront hides empty values automatically.
   */
  specifications?:
    | {
        label?: string | null;
        value?: string | null;
        /**
         * Optional group, such as “Size” or “Performance”.
         */
        group?: string | null;
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Fill this only when there is a size guide. Leave empty and the storefront will hide this section.
   */
  sizeGuide?: {
    title?: string | null;
    cornerLabel?: string | null;
    columns?:
      | {
          label?: string | null;
          id?: string | null;
        }[]
      | null;
    rows?:
      | {
          label?: string | null;
          values?:
            | {
                value?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  applications?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Used for the Product Detail “Application Scenarios” cards, such as “Fire rescue / Emergency response / Disaster relief”. If empty, the storefront can keep using the legacy template or scenario text.
   */
  scenarios?:
    | {
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Used for image groups below the detail page. Recommended legacy groups: scene images / renderings / model images. Do not add groups without matching images. Image count is unlimited; the storefront uses carousel and lazy loading.
   */
  visualGroups?:
    | {
        variant?:
          | ('gallery' | 'scene' | 'modeling' | 'model' | 'detail' | 'certificate' | 'comparison')
          | null;
        title?: string | null;
        description?: string | null;
        images?:
          | {
              file: number | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * P3+ extended field: certifications and certificates.
   */
  certifications?:
    | {
        name?: string | null;
        issuer?: string | null;
        certNumber?: string | null;
        status?: ('valid' | 'expired' | 'pending' | 'not-applicable') | null;
        validUntil?: string | null;
        attachment?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * P3+ extended field: quality evidence.
   */
  qualityEvidence?:
    | {
        type?: ('certificate' | 'test-report' | 'inspection' | 'case-study' | 'other') | null;
        status?: string | null;
        title?: string | null;
        description?: string | null;
        attachment?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  careInstructions?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Enter the questions and answers shown on this product detail page directly; no FAQ relationship is required first.
   */
  productFaqs?:
    | {
        question?: string | null;
        answer?: string | null;
        id?: string | null;
      }[]
    | null;
  faqs?: (number | Faq)[] | null;
  video?: (number | null) | Media;
  /**
   * Enter 1, 2, or 3. Smaller numbers appear first. Required before publishing; use 0 only for draft temporary saves.
   */
  displayOrder?: number | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Create and maintain one horizontal storefront product category. After saving, assign products to this group so the storefront product center displays the category and its products.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-groups".
 */
export interface ProductGroup {
  id: number;
  /**
   * Group title visitors see in the Product Center, such as “Cleanroom Chemical & Medical Protection”.
   */
  name: string;
  /**
   * Shown as the summary beside the Product Center group title. If empty, the storefront uses subcategories or product names under this group.
   */
  description?: string | null;
  showOnFrontend?: boolean | null;
  /**
   * Use 1, 2, 3… Lower numbers appear first on the storefront.
   */
  order?: number | null;
  /**
   * Used by the system for links, filters, and product grouping. Do not change it casually after creation.
   */
  groupId: string;
  /**
   * This appears in the URL. Keep it aligned with the group key. Usually leave it empty for auto-generation and avoid changing it after saving.
   */
  slug: string;
  seo?: {
    /**
     * Shown in the browser title and search-result title. If empty, the page name is usually used.
     */
    title?: string | null;
    /**
     * Summary text for search results. Keep it within 200 Chinese characters when possible.
     */
    description?: string | null;
    /**
     * Separate with commas; 3–7 keywords are recommended. Search engines no longer rely on this heavily, so enter only core terms.
     */
    keywords?: string | null;
    /**
     * May be used as the preview image when the page is shared on WeChat, social media, or chat apps.
     */
    ogImage?: (number | null) | Media;
    /**
     * Usually leave this off. When enabled, this page will be kept out of search results where possible.
     */
    noindex?: boolean | null;
    /**
     * Tells search engines which URL is the canonical version. Leave empty if unsure.
     */
    canonical?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * The system generates this from the upload context or file name automatically.
   */
  alt: string;
  caption?: string | null;
  credit?: string | null;
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  folder?: ('brand' | 'products' | 'news' | 'icons' | 'video' | 'pdf' | 'misc') | null;
  /**
   * Maintained automatically by the P2.S4 media reference statistics hook.
   */
  usageCount?: number | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    mobile?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  scope: 'global' | 'page' | 'product' | 'news';
  pageRef?: (number | null) | Page;
  productRef?: (number | null) | Product;
  newsRef?: (number | null) | News;
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Enter 1, 2, or 3. Smaller numbers appear first.
   */
  order?: number | null;
  isPublished: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Fixed page identifier. Do not change it after creation.
   */
  pageKey:
    | 'home'
    | 'about'
    | 'products-index'
    | 'solutions'
    | 'news-index'
    | 'franchise'
    | 'contact'
    | 'privacy'
    | 'cookies'
    | 'terms';
  title: string;
  /**
   * Fixed page route slug. Use an empty string for home.
   */
  slug?: string | null;
  hero?: {
    enabled?: boolean | null;
    variant?: ('video-bg' | 'image-bg' | 'carousel' | 'plain') | null;
    title?: string | null;
    subtitle?: string | null;
    backgroundImage?: (number | null) | Media;
    backgroundVideo?: (number | null) | Media;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  blocks?:
    | (
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
        | {
            layout?: ('media-left' | 'media-right') | null;
            media?: (number | null) | Media;
            title?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaText';
          }
        | {
            title?: string | null;
            /**
             * 旧站遗留字段，新内容不要使用。
             */
            category?: (number | null) | ProductCategory;
            products?: (number | Product)[] | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'productShowcase';
          }
        | {
            title?: string | null;
            category?: ('news' | 'event' | 'announcement' | 'exhibition') | null;
            news?: (number | News)[] | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsList';
          }
        | FaqContentBlock
        | {
            title?: string | null;
            description?: string | null;
            primaryLabel?: string | null;
            primaryHref?: string | null;
            secondaryLabel?: string | null;
            secondaryHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            items?:
              | {
                  value: string;
                  label: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            title?: string | null;
            showForm?: boolean | null;
            showMap?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contact';
          }
      )[]
    | null;
  seo?: {
    /**
     * Shown in the browser title and search-result title. If empty, the page name is usually used.
     */
    title?: string | null;
    /**
     * Summary text for search results. Keep it within 200 Chinese characters when possible.
     */
    description?: string | null;
    /**
     * Separate with commas; 3–7 keywords are recommended. Search engines no longer rely on this heavily, so enter only core terms.
     */
    keywords?: string | null;
    /**
     * May be used as the preview image when the page is shared on WeChat, social media, or chat apps.
     */
    ogImage?: (number | null) | Media;
    /**
     * Usually leave this off. When enabled, this page will be kept out of search results where possible.
     */
    noindex?: boolean | null;
    /**
     * Tells search engines which URL is the canonical version. Leave empty if unsure.
     */
    canonical?: string | null;
  };
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Legacy subcategory data. For daily maintenance, use Product Groups and Products first.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories".
 */
export interface ProductCategory {
  id: number;
  /**
   * Legacy site category ID. Do not rename it.
   */
  categoryId: string;
  /**
   * Usually the same as categoryId. If empty, the P2.S3 placeholder is generated from categoryId.
   */
  slug: string;
  name: string;
  description?: string | null;
  /**
   * Product groups used by the storefront Product Center. Choose this first when creating categories.
   */
  productGroup?: (number | null) | ProductGroup;
  /**
   * Legacy fixed-group field, kept only for historical data compatibility.
   */
  group?:
    | (
        | 'fire-rescue'
        | 'electrical-protection'
        | 'thermal-welding'
        | 'chemical-medical'
        | 'water-rescue'
      )
    | null;
  parent?: (number | null) | ProductCategory;
  cover?: (number | null) | Media;
  icon?: (number | null) | Media;
  /**
   * Enter 1, 2, or 3. Smaller numbers appear first.
   */
  order?: number | null;
  seo?: {
    /**
     * Shown in the browser title and search-result title. If empty, the page name is usually used.
     */
    title?: string | null;
    /**
     * Summary text for search results. Keep it within 200 Chinese characters when possible.
     */
    description?: string | null;
    /**
     * Separate with commas; 3–7 keywords are recommended. Search engines no longer rely on this heavily, so enter only core terms.
     */
    keywords?: string | null;
    /**
     * May be used as the preview image when the page is shared on WeChat, social media, or chat apps.
     */
    ogImage?: (number | null) | Media;
    /**
     * Usually leave this off. When enabled, this page will be kept out of search results where possible.
     */
    noindex?: boolean | null;
    /**
     * Tells search engines which URL is the canonical version. Leave empty if unsure.
     */
    canonical?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * Shown under the title in news lists and detail pages. If empty, the storefront extracts text from the article body.
   */
  excerpt?: string | null;
  author?: string | null;
  /**
   * Static cover used in news lists and detail pages. Video news can omit it, but upload one when there is no video to avoid a storefront placeholder.
   */
  cover?: (number | null) | Media;
  /**
   * Video preview for the top three featured News Center cards. Chinese and English pages use this video; the cover image is used as the poster frame. If no video is uploaded, the storefront falls back to the cover image.
   */
  featuredVideo?: (number | null) | Media;
  /**
   * Featured-news preview video for Russian pages. Replace it when Russian material is available. If empty, Russian pages fall back to the English/Chinese video.
   */
  featuredVideoRu?: (number | null) | Media;
  category: 'news' | 'event' | 'announcement' | 'exhibition';
  /**
   * Written automatically when publishing. Used for storefront dates and news sorting.
   */
  publishedAt?: string | null;
  /**
   * Controls the order of the three featured News Center cards and homepage news preview. Enter 1, 2, or 3; smaller numbers appear first. Empty or 0 lets publish time fill the slot.
   */
  featuredOrder?: number | null;
  /**
   * When checked, this appears in the homepage and News Center featured area. If a featured position is set, it is also included in featured sorting automatically.
   */
  isFeatured?: boolean | null;
  /**
   * The article body supports paragraphs, headings, lists, and media images. Inserted images appear as standalone image sections on the storefront detail page.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  relatedNews?: (number | News)[] | null;
  relatedProducts?: (number | Product)[] | null;
  /**
   * Leave empty to generate from the title. P2.S4 adds full pinyin and uniqueness handling.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqContentBlock".
 */
export interface FaqContentBlock {
  title?: string | null;
  faqs?: (number | Faq)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * Maintain the Solutions page, header dropdown, and footer navigation. Created, removed, or reordered published items are synced to the storefront.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions".
 */
export interface Solution {
  id: number;
  /**
   * Storefront card title, such as “Power & Energy” or “Emergency Rescue”.
   */
  title: string;
  /**
   * Description shown on the storefront card. Recommended length: 40–90 Chinese characters.
   */
  summary?: string | null;
  /**
   * Main image used by the storefront solution card.
   */
  cover?: (number | null) | Media;
  /**
   * Controls display order on the Solutions page, header dropdown, and footer navigation. Enter 1, 2, or 3; smaller numbers appear first.
   */
  order?: number | null;
  features?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  productTags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Usually optional. Fill this only when a longer explanation is needed.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Written automatically when publishing. Used by admin lists and storefront sync checks.
   */
  publishedAt?: string | null;
  /**
   * Stable identifier for storefront anchors and import updates, such as power-energy. Usually do not change it.
   */
  solutionId: string;
  /**
   * Storefront URL slug. Leave empty to generate from the system key; usually do not edit manually.
   */
  slug: string;
  /**
   * Reserved internal field. The storefront “View products” action goes to the Products page and this relationship is not shown in lists.
   */
  relatedProductGroups?: (number | ProductGroup)[] | null;
  /**
   * Legacy field. For new solutions, maintain Related Product Groups and Related Products first.
   */
  relatedCategories?: (number | ProductCategory)[] | null;
  /**
   * Reserved internal field. The storefront “View products” action currently goes to the Products page.
   */
  relatedProducts?: (number | Product)[] | null;
  /**
   * Internal compatibility field. Published solution items currently appear as large solution cards on the storefront.
   */
  isFeatured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Site-search analytics: popular keywords, zero-result queries, and lightweight click-through rate.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search-logs".
 */
export interface SearchLog {
  id: number;
  /**
   * Distinguishes a search event from a search-result click.
   */
  eventType: 'search' | 'result-click';
  query: string;
  /**
   * Records the storefront language version used by the visitor.
   */
  locale: 'zh' | 'en' | 'ru';
  hits: number;
  resultId?: string | null;
  resultTitle?: string | null;
  resultType?: ('product' | 'solution' | 'industry-case' | 'news' | 'page' | 'faq') | null;
  resultUrl?: string | null;
  userId?: string | null;
  ip: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Choose admin permission roles.
   */
  role: number | Role;
  /**
   * Maintained automatically by the P2.S4/P4 login hook.
   */
  lastLoginAt?: string | null;
  /**
   * Used when P4 two-factor authentication is enabled.
   */
  twoFactorEnabled?: boolean | null;
  /**
   * Encrypt this after P4 is enabled; never output it in logs.
   */
  twoFactorSecret?: string | null;
  /**
   * Soft-delete marker retained for audit traceability.
   */
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  /**
   * Reserved for a permission matrix. Phase 1 super-admin uses * for full access.
   */
  permissions:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  user?: (number | null) | User;
  userEmail: string;
  action:
    | 'login'
    | 'logout'
    | 'login_failed'
    | 'create'
    | 'update'
    | 'delete'
    | 'restore'
    | 'publish'
    | 'unpublish'
    | 'upload'
    | 'media-delete'
    | 'form-submitted'
    | 'role-change'
    | 'permission-grant'
    | 'permission-revoke'
    | 'config-change';
  collection?: string | null;
  documentId?: string | null;
  documentSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  ip?: string | null;
  userAgent?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'product-groups';
        value: number | ProductGroup;
      } | null)
    | ({
        relationTo: 'product-categories';
        value: number | ProductCategory;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'solutions';
        value: number | Solution;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'search-logs';
        value: number | SearchLog;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'roles';
        value: number | Role;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  name?: T;
  country?: T;
  company?: T;
  position?: T;
  phone?: T;
  email?: T;
  inquiryType?: T;
  message?: T;
  productRef?: T;
  status?: T;
  assignedTo?: T;
  notes?:
    | T
    | {
        at?: T;
        user?: T;
        text?: T;
        id?: T;
      };
  sourceUrl?: T;
  sourceLocale?: T;
  ip?: T;
  userAgent?: T;
  consentAcceptedAt?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-groups_select".
 */
export interface ProductGroupsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  showOnFrontend?: T;
  order?: T;
  groupId?: T;
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
        noindex?: T;
        canonical?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  categoryId?: T;
  slug?: T;
  name?: T;
  description?: T;
  productGroup?: T;
  group?: T;
  parent?: T;
  cover?: T;
  icon?: T;
  order?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
        noindex?: T;
        canonical?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  productId?: T;
  sku?: T;
  model?: T;
  name?: T;
  slug?: T;
  productGroup?: T;
  images?:
    | T
    | {
        file?: T;
        id?: T;
      };
  description?: T;
  standards?:
    | T
    | {
        value?: T;
        id?: T;
      };
  sizeRange?:
    | T
    | {
        value?: T;
        id?: T;
      };
  materials?:
    | T
    | {
        value?: T;
        id?: T;
      };
  features?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  sellingPoints?:
    | T
    | {
        title?: T;
        text?: T;
        icon?: T;
        id?: T;
      };
  specifications?:
    | T
    | {
        label?: T;
        value?: T;
        group?: T;
        order?: T;
        id?: T;
      };
  sizeGuide?:
    | T
    | {
        title?: T;
        cornerLabel?: T;
        columns?:
          | T
          | {
              label?: T;
              id?: T;
            };
        rows?:
          | T
          | {
              label?: T;
              values?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  applications?:
    | T
    | {
        value?: T;
        id?: T;
      };
  scenarios?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  visualGroups?:
    | T
    | {
        variant?: T;
        title?: T;
        description?: T;
        images?:
          | T
          | {
              file?: T;
              id?: T;
            };
        id?: T;
      };
  certifications?:
    | T
    | {
        name?: T;
        issuer?: T;
        certNumber?: T;
        status?: T;
        validUntil?: T;
        attachment?: T;
        id?: T;
      };
  qualityEvidence?:
    | T
    | {
        type?: T;
        status?: T;
        title?: T;
        description?: T;
        attachment?: T;
        id?: T;
      };
  careInstructions?:
    | T
    | {
        value?: T;
        id?: T;
      };
  productFaqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  faqs?: T;
  video?: T;
  displayOrder?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions_select".
 */
export interface SolutionsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  cover?: T;
  order?: T;
  features?:
    | T
    | {
        value?: T;
        id?: T;
      };
  productTags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  content?: T;
  publishedAt?: T;
  solutionId?: T;
  slug?: T;
  relatedProductGroups?: T;
  relatedCategories?: T;
  relatedProducts?: T;
  isFeatured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  author?: T;
  cover?: T;
  featuredVideo?: T;
  featuredVideoRu?: T;
  category?: T;
  publishedAt?: T;
  featuredOrder?: T;
  isFeatured?: T;
  content?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  relatedNews?: T;
  relatedProducts?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  pageKey?: T;
  title?: T;
  slug?: T;
  hero?:
    | T
    | {
        enabled?: T;
        variant?: T;
        title?: T;
        subtitle?: T;
        backgroundImage?: T;
        backgroundVideo?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  blocks?:
    | T
    | {
        content?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        mediaText?:
          | T
          | {
              layout?: T;
              media?: T;
              title?: T;
              content?: T;
              ctaLabel?: T;
              ctaHref?: T;
              id?: T;
              blockName?: T;
            };
        productShowcase?:
          | T
          | {
              title?: T;
              category?: T;
              products?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        newsList?:
          | T
          | {
              title?: T;
              category?: T;
              news?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        faq?: T | FaqContentBlockSelect<T>;
        cta?:
          | T
          | {
              title?: T;
              description?: T;
              primaryLabel?: T;
              primaryHref?: T;
              secondaryLabel?: T;
              secondaryHref?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contact?:
          | T
          | {
              title?: T;
              showForm?: T;
              showMap?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
        noindex?: T;
        canonical?: T;
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqContentBlock_select".
 */
export interface FaqContentBlockSelect<T extends boolean = true> {
  title?: T;
  faqs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  scope?: T;
  pageRef?: T;
  productRef?: T;
  newsRef?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  order?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  folder?: T;
  usageCount?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        mobile?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search-logs_select".
 */
export interface SearchLogsSelect<T extends boolean = true> {
  eventType?: T;
  query?: T;
  locale?: T;
  hits?: T;
  resultId?: T;
  resultTitle?: T;
  resultType?: T;
  resultUrl?: T;
  userId?: T;
  ip?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  lastLoginAt?: T;
  twoFactorEnabled?: T;
  twoFactorSecret?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  permissions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  user?: T;
  userEmail?: T;
  action?: T;
  collection?: T;
  documentId?: T;
  documentSnapshot?: T;
  ip?: T;
  userAgent?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  mainNav?:
    | {
        label: string;
        href: string;
        icon?: (number | null) | Media;
        target?: ('_self' | '_blank') | null;
        children?:
          | {
              label: string;
              href: string;
              icon?: (number | null) | Media;
              target?: ('_self' | '_blank') | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footerNav?:
    | {
        heading?: string | null;
        items?:
          | {
              label: string;
              href: string;
              icon?: (number | null) | Media;
              target?: ('_self' | '_blank') | null;
              children?:
                | {
                    label: string;
                    href: string;
                    icon?: (number | null) | Media;
                    target?: ('_self' | '_blank') | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  mobileNav?:
    | {
        label: string;
        href: string;
        icon?: (number | null) | Media;
        target?: ('_self' | '_blank') | null;
        children?:
          | {
              label: string;
              href: string;
              icon?: (number | null) | Media;
              target?: ('_self' | '_blank') | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  contact?: {
    phone?: string | null;
    email?: string | null;
    address?: string | null;
  };
  coordinates?: {
    lat?: number | null;
    lng?: number | null;
    zoom?: number | null;
  };
  socials?:
    | {
        platform: 'wechat' | 'weibo' | 'linkedin' | 'youtube' | 'facebook' | 'x' | 'other';
        url: string;
        icon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  siteName: string;
  tagline?: string | null;
  logo: {
    light: number | Media;
    dark: number | Media;
  };
  themeColor: string;
  defaultSeo?: {
    /**
     * Shown in the browser title and search-result title. If empty, the page name is usually used.
     */
    title?: string | null;
    /**
     * Summary text for search results. Keep it within 200 Chinese characters when possible.
     */
    description?: string | null;
    /**
     * Separate with commas; 3–7 keywords are recommended. Search engines no longer rely on this heavily, so enter only core terms.
     */
    keywords?: string | null;
    /**
     * May be used as the preview image when the page is shared on WeChat, social media, or chat apps.
     */
    ogImage?: (number | null) | Media;
    /**
     * Usually leave this off. When enabled, this page will be kept out of search results where possible.
     */
    noindex?: boolean | null;
    /**
     * Tells search engines which URL is the canonical version. Leave empty if unsure.
     */
    canonical?: string | null;
  };
  mapServiceByLocale?:
    | {
        locale: 'zh' | 'en' | 'ru';
        service: 'amap' | 'google';
        id?: string | null;
      }[]
    | null;
  cookieConsent?: {
    enabled?: boolean | null;
    title?: string | null;
    description?: string | null;
    acceptLabel?: string | null;
    rejectLabel?: string | null;
    essentialOnlyLabel?: string | null;
  };
  analytics?: {
    enabled?: boolean | null;
    /**
     * Only save the public website ID. Do not enter an API key.
     */
    umamiWebsiteId?: string | null;
  };
  icp: string;
  /**
   * [NEEDS INPUT] Format: public security registration number.
   */
  publicSecurityRecord?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  mainNav?:
    | T
    | {
        label?: T;
        href?: T;
        icon?: T;
        target?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              icon?: T;
              target?: T;
              id?: T;
            };
        id?: T;
      };
  footerNav?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              label?: T;
              href?: T;
              icon?: T;
              target?: T;
              children?:
                | T
                | {
                    label?: T;
                    href?: T;
                    icon?: T;
                    target?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  mobileNav?:
    | T
    | {
        label?: T;
        href?: T;
        icon?: T;
        target?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              icon?: T;
              target?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  contact?:
    | T
    | {
        phone?: T;
        email?: T;
        address?: T;
      };
  coordinates?:
    | T
    | {
        lat?: T;
        lng?: T;
        zoom?: T;
      };
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        icon?: T;
        id?: T;
      };
  siteName?: T;
  tagline?: T;
  logo?:
    | T
    | {
        light?: T;
        dark?: T;
      };
  themeColor?: T;
  defaultSeo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
        noindex?: T;
        canonical?: T;
      };
  mapServiceByLocale?:
    | T
    | {
        locale?: T;
        service?: T;
        id?: T;
      };
  cookieConsent?:
    | T
    | {
        enabled?: T;
        title?: T;
        description?: T;
        acceptLabel?: T;
        rejectLabel?: T;
        essentialOnlyLabel?: T;
      };
  analytics?:
    | T
    | {
        enabled?: T;
        umamiWebsiteId?: T;
      };
  icp?: T;
  publicSecurityRecord?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}
