/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'form-submissions': FormSubmission;
    'product-groups': ProductGroup;
    'product-categories': ProductCategory;
    products: Product;
    solutions: Solution;
    news: News;
    pages: Page;
    faqs: Faq;
    media: Media;
    'search-logs': SearchLog;
    users: User;
    roles: Role;
    'audit-logs': AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'product-groups': ProductGroupsSelect<false> | ProductGroupsSelect<true>;
    'product-categories': ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    solutions: SolutionsSelect<false> | SolutionsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'search-logs': SearchLogsSelect<false> | SearchLogsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents':
      | PayloadLockedDocumentsSelect<false>
      | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('zh' | 'en' | 'ru')
    | ('zh' | 'en' | 'ru')[];
  globals: {
    navigation: Navigation;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'zh' | 'en' | 'ru';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  name: string;
  country?: string | null;
  company?: string | null;
  position?: string | null;
  phone: string;
  email: string;
  inquiryType: 'franchise' | 'message';
  message: string;
  productRef?: (number | null) | Product;
  status: 'new' | 'processing' | 'replied' | 'closed';
  /**
   * 直接填写线下跟进人姓名。
   */
  assignedTo?: string | null;
  notes?:
    | {
        at: string;
        /**
         * 直接填写跟进人姓名。
         */
        user?: string | null;
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 由提交页面自动记录。
   */
  sourceUrl?: string | null;
  sourceLocale?: ('zh' | 'en' | 'ru') | null;
  ip?: string | null;
  userAgent?: string | null;
  consentAcceptedAt: string;
  /**
   * 仅系统在软删除流程中写入；为空表示当前记录正常。
   */
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Maintain storefront product cards and detail pages. Product numbers and names identify products and build links; a real main image is required before publishing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * 稳定编号，用于前台详情页链接。创建后不建议修改。
   */
  productId: string;
  sku?: string | null;
  /**
   * 可选。展示在前台详情页主图右侧和规格参数区。
   */
  model?: string | null;
  name: string;
  /**
   * 默认从 productId 生成；P2.S4 接入完整拼音与唯一性处理。
   */
  slug: string;
  /**
   * 必填。创建产品时先选择产品大类，前台产品中心会直接把该产品放到这个大类下面。
   */
  productGroup: number | ProductGroup;
  images?:
    | {
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * 展示在主图右侧摘要，也会作为“商品介绍”区块的概述内容。
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  standards?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  sizeRange?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  materials?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 没有特点时可不添加。前台只展示已填写的特点。
   */
  features?:
    | {
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * P3+ 扩展字段：营销卖点。
   */
  sellingPoints?:
    | {
        title?: string | null;
        text?: string | null;
        icon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * 按旧版详情页参数表填写。可添加：型号、执行标准、颜色、尺码、材料、类别、结构等；没有的数据不要添加，前台会自动隐藏空项。
   */
  specifications?:
    | {
        label?: string | null;
        value?: string | null;
        /**
         * 可选分组，如“尺寸”“性能”。
         */
        group?: string | null;
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 有尺码对应表时再填写；没有可留空，前台不会展示该区块。
   */
  sizeGuide?: {
    title?: string | null;
    cornerLabel?: string | null;
    columns?:
      | {
          label?: string | null;
          id?: string | null;
        }[]
      | null;
    rows?:
      | {
          label?: string | null;
          values?:
            | {
                value?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  applications?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 用于产品详情页“适用场景”卡片，例如“灭火救援 / 应急抢险 / 灾害处置”。不填时前台可继续使用旧模板或适用场景文本。
   */
  scenarios?:
    | {
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 用于详情页下方图片分组。建议按旧站整理为“场景图 / 建模图 / 模特上身图”；没有对应图片时不要添加。图片数量不限，前台用轮播和懒加载展示。
   */
  visualGroups?:
    | {
        variant?:
          | ('gallery' | 'scene' | 'modeling' | 'model' | 'detail' | 'certificate' | 'comparison')
          | null;
        title?: string | null;
        description?: string | null;
        images?:
          | {
              file: number | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * P3+ 扩展字段：认证与证书。
   */
  certifications?:
    | {
        name?: string | null;
        issuer?: string | null;
        certNumber?: string | null;
        status?: ('valid' | 'expired' | 'pending' | 'not-applicable') | null;
        validUntil?: string | null;
        attachment?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * P3+ 扩展字段：质量证据。
   */
  qualityEvidence?:
    | {
        type?: ('certificate' | 'test-report' | 'inspection' | 'case-study' | 'other') | null;
        status?: string | null;
        title?: string | null;
        description?: string | null;
        attachment?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  careInstructions?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 直接填写该产品详情页展示的问题和答案；不需要先去关联 FAQ。
   */
  productFaqs?:
    | {
        question?: string | null;
        answer?: string | null;
        id?: string | null;
      }[]
    | null;
  faqs?: (number | Faq)[] | null;
  video?: (number | null) | Media;
  /**
   * 直接填 1、2、3；数字越小越靠前；发布前必须填写，0 仅用于草稿暂存。
   */
  displayOrder?: number | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Create and maintain one horizontal storefront product category. After saving, assign products to this group so the storefront product center displays the category and its products.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-groups".
 */
export interface ProductGroup {
  id: number;
  /**
   * 用户在产品中心看到的大类标题，例如“洁净化学与医疗防护”。
   */
  name: string;
  /**
   * 显示在产品中心大类标题旁边的摘要位置。不填时，前台会优先用该大类下的子分类或产品名称补充。
   */
  description?: string | null;
  showOnFrontend?: boolean | null;
  /**
   * Use 1, 2, 3… Lower numbers appear first on the storefront.
   */
  order?: number | null;
  /**
   * 给系统识别用，会用于链接、筛选和产品归类。创建后不要随意修改。
   */
  groupId: string;
  /**
   * 会出现在网址里，建议和“大类英文标识”保持一致。一般留空自动生成即可，保存后不建议频繁修改。
   */
  slug: string;
  seo?: {
    /**
     * 显示在浏览器标题和搜索结果标题里；不填时通常会使用页面名称。
     */
    title?: string | null;
    /**
     * 搜索结果里的摘要文案，建议控制在 200 字以内。
     */
    description?: string | null;
    /**
     * 用逗号分隔，建议 3-7 个。现在搜索引擎不强依赖它，填核心词即可。
     */
    keywords?: string | null;
    /**
     * 页面被分享到微信、社媒或聊天软件时，可能会作为预览图。
     */
    ogImage?: (number | null) | Media;
    /**
     * 一般不要开启。开启后，这个页面会尽量不出现在搜索结果里。
     */
    noindex?: boolean | null;
    /**
     * 用于告诉搜索引擎哪个地址是主版本；不懂可以留空。
     */
    canonical?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * 系统会根据上传场景或文件名自动生成。
   */
  alt: string;
  caption?: string | null;
  credit?: string | null;
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  folder?: ('brand' | 'products' | 'news' | 'icons' | 'video' | 'pdf' | 'misc') | null;
  /**
   * P2.S4 媒体引用统计 hook 自动维护。
   */
  usageCount?: number | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    mobile?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  scope: 'global' | 'page' | 'product' | 'news';
  pageRef?: (number | null) | Page;
  productRef?: (number | null) | Product;
  newsRef?: (number | null) | News;
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 直接填 1、2、3；数字越小越靠前。
   */
  order?: number | null;
  isPublished: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * 固定页面标识，创建后不要修改。
   */
  pageKey:
    | 'home'
    | 'about'
    | 'products-index'
    | 'solutions'
    | 'news-index'
    | 'franchise'
    | 'contact'
    | 'privacy'
    | 'cookies'
    | 'terms';
  title: string;
  /**
   * 固定页面路由 slug；home 可填空字符串。
   */
  slug?: string | null;
  hero?: {
    enabled?: boolean | null;
    variant?: ('video-bg' | 'image-bg' | 'carousel' | 'plain') | null;
    title?: string | null;
    subtitle?: string | null;
    backgroundImage?: (number | null) | Media;
    backgroundVideo?: (number | null) | Media;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  blocks?:
    | (
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
        | {
            layout?: ('media-left' | 'media-right') | null;
            media?: (number | null) | Media;
            title?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            ctaLabel?: string | null;
            ctaHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaText';
          }
        | {
            title?: string | null;
            /**
             * 旧站遗留字段，新内容不要使用。
             */
            category?: (number | null) | ProductCategory;
            products?: (number | Product)[] | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'productShowcase';
          }
        | {
            title?: string | null;
            category?: ('news' | 'event' | 'announcement' | 'exhibition') | null;
            news?: (number | News)[] | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsList';
          }
        | FaqContentBlock
        | {
            title?: string | null;
            description?: string | null;
            primaryLabel?: string | null;
            primaryHref?: string | null;
            secondaryLabel?: string | null;
            secondaryHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            items?:
              | {
                  value: string;
                  label: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            title?: string | null;
            showForm?: boolean | null;
            showMap?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contact';
          }
      )[]
    | null;
  seo?: {
    /**
     * 显示在浏览器标题和搜索结果标题里；不填时通常会使用页面名称。
     */
    title?: string | null;
    /**
     * 搜索结果里的摘要文案，建议控制在 200 字以内。
     */
    description?: string | null;
    /**
     * 用逗号分隔，建议 3-7 个。现在搜索引擎不强依赖它，填核心词即可。
     */
    keywords?: string | null;
    /**
     * 页面被分享到微信、社媒或聊天软件时，可能会作为预览图。
     */
    ogImage?: (number | null) | Media;
    /**
     * 一般不要开启。开启后，这个页面会尽量不出现在搜索结果里。
     */
    noindex?: boolean | null;
    /**
     * 用于告诉搜索引擎哪个地址是主版本；不懂可以留空。
     */
    canonical?: string | null;
  };
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * 兼容旧数据的细分分类。日常维护优先使用“产品大类”和“产品”。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories".
 */
export interface ProductCategory {
  id: number;
  /**
   * 旧站 category id，不可改名。
   */
  categoryId: string;
  /**
   * 通常与 categoryId 一致；留空时 P2.S3 placeholder 从 categoryId 生成。
   */
  slug: string;
  name: string;
  description?: string | null;
  /**
   * 前台产品中心使用的大类。新增分类请优先选择这里。
   */
  productGroup?: (number | null) | ProductGroup;
  /**
   * 旧版固定大类字段，仅用于兼容历史数据。
   */
  group?:
    | (
        | 'fire-rescue'
        | 'electrical-protection'
        | 'thermal-welding'
        | 'chemical-medical'
        | 'water-rescue'
      )
    | null;
  parent?: (number | null) | ProductCategory;
  cover?: (number | null) | Media;
  icon?: (number | null) | Media;
  /**
   * 直接填 1、2、3；数字越小越靠前。
   */
  order?: number | null;
  seo?: {
    /**
     * 显示在浏览器标题和搜索结果标题里；不填时通常会使用页面名称。
     */
    title?: string | null;
    /**
     * 搜索结果里的摘要文案，建议控制在 200 字以内。
     */
    description?: string | null;
    /**
     * 用逗号分隔，建议 3-7 个。现在搜索引擎不强依赖它，填核心词即可。
     */
    keywords?: string | null;
    /**
     * 页面被分享到微信、社媒或聊天软件时，可能会作为预览图。
     */
    ogImage?: (number | null) | Media;
    /**
     * 一般不要开启。开启后，这个页面会尽量不出现在搜索结果里。
     */
    noindex?: boolean | null;
    /**
     * 用于告诉搜索引擎哪个地址是主版本；不懂可以留空。
     */
    canonical?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * 显示在新闻列表和详情页标题下方；留空时前台会从正文截取。
   */
  excerpt?: string | null;
  author?: string | null;
  /**
   * 用于新闻列表和详情页的静态封面。视频新闻可不上传；没有视频时建议上传，避免前台只显示占位图。
   */
  cover?: (number | null) | Media;
  /**
   * 用于新闻中心顶部三张大卡片的视频预览；封面图会作为视频封面帧。不上传视频时，前台会退回显示封面图。
   */
  featuredVideo?: (number | null) | Media;
  category: 'news' | 'event' | 'announcement' | 'exhibition';
  /**
   * 系统在点击发布时自动写入，用于前台显示日期和新闻排序。
   */
  publishedAt?: string | null;
  /**
   * 控制新闻中心顶部三张重点新闻卡片和首页新闻预览顺序；直接填 1、2、3，数字越小越靠前。留空或 0 表示按发布时间补位。
   */
  featuredOrder?: number | null;
  /**
   * 勾选后进入首页和新闻中心顶部重点位；如果已填写重点位置，也会自动作为重点新闻参与排序。
   */
  isFeatured?: boolean | null;
  /**
   * 新闻正文支持段落、标题、列表和媒体图片；插入图片后，前台详情页会以独立图片区块展示。
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  relatedNews?: (number | News)[] | null;
  relatedProducts?: (number | Product)[] | null;
  /**
   * 留空从标题生成；P2.S4 接入完整拼音与唯一性处理。
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqContentBlock".
 */
export interface FaqContentBlock {
  title?: string | null;
  faqs?: (number | Faq)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * Maintain the Solutions page, header dropdown, and footer navigation. Created, removed, or reordered published items are synced to the storefront.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions".
 */
export interface Solution {
  id: number;
  /**
   * 前台卡片标题，例如“电力与能源”“应急救援”。
   */
  title: string;
  /**
   * 前台卡片展示的一段说明，建议 40-90 个中文字符。
   */
  summary?: string | null;
  /**
   * 前台解决方案卡片使用的主图。
   */
  cover?: (number | null) | Media;
  /**
   * 控制解决方案页面、顶部下拉菜单与页脚导航的展示顺序；直接填 1、2、3，数字越小越靠前。
   */
  order?: number | null;
  features?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  productTags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 一般可留空；需要补充长文说明时再填写。
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * 系统在点击发布时自动写入，用于后台列表和前台同步判断。
   */
  publishedAt?: string | null;
  /**
   * 用于前台锚点和导入更新的稳定标识，例如 power-energy。通常不要修改。
   */
  solutionId: string;
  /**
   * 前台访问链接后缀；留空时从系统标识生成，通常不要手动修改。
   */
  slug: string;
  /**
   * 内部预留字段。当前前台“查看产品”统一进入产品页，不在列表展示关联关系。
   */
  relatedProductGroups?: (number | ProductGroup)[] | null;
  /**
   * 旧站遗留字段，新方案优先维护“关联产品大类”和“关联产品”。
   */
  relatedCategories?: (number | ProductCategory)[] | null;
  /**
   * 内部预留字段。当前前台“查看产品”统一进入产品页。
   */
  relatedProducts?: (number | Product)[] | null;
  /**
   * 内部兼容字段。当前前台解决方案集合里的发布内容都会作为上方大图方案展示。
   */
  isFeatured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * 站内搜索统计：热门关键词、零结果查询与轻量点击率。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search-logs".
 */
export interface SearchLog {
  id: number;
  /**
   * 区分一次搜索还是搜索结果点击。
   */
  eventType: 'search' | 'result-click';
  query: string;
  /**
   * 记录用户使用的前台语言版本。
   */
  locale: 'zh' | 'en' | 'ru';
  hits: number;
  resultId?: string | null;
  resultTitle?: string | null;
  resultType?: ('product' | 'solution' | 'industry-case' | 'news' | 'page' | 'faq') | null;
  resultUrl?: string | null;
  userId?: string | null;
  ip: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * 选择后台权限角色。
   */
  role: number | Role;
  /**
   * P2.S4/P4 登录 hook 自动维护。
   */
  lastLoginAt?: string | null;
  /**
   * P4 启用二次验证时使用。
   */
  twoFactorEnabled?: boolean | null;
  /**
   * P4 启用后需加密存储；不要在日志中输出。
   */
  twoFactorSecret?: string | null;
  /**
   * 软删除标记；保留审计追溯。
   */
  deletedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  /**
   * 权限矩阵预留；一期 super-admin 使用 * 全权限。
   */
  permissions:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  user?: (number | null) | User;
  userEmail: string;
  action:
    | 'login'
    | 'logout'
    | 'login_failed'
    | 'create'
    | 'update'
    | 'delete'
    | 'restore'
    | 'publish'
    | 'unpublish'
    | 'upload'
    | 'media-delete'
    | 'form-submitted'
    | 'role-change'
    | 'permission-grant'
    | 'permission-revoke'
    | 'config-change';
  collection?: string | null;
  documentId?: string | null;
  documentSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  ip?: string | null;
  userAgent?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'product-groups';
        value: number | ProductGroup;
      } | null)
    | ({
        relationTo: 'product-categories';
        value: number | ProductCategory;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'solutions';
        value: number | Solution;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'search-logs';
        value: number | SearchLog;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'roles';
        value: number | Role;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  name?: T;
  country?: T;
  company?: T;
  position?: T;
  phone?: T;
  email?: T;
  inquiryType?: T;
  message?: T;
  productRef?: T;
  status?: T;
  assignedTo?: T;
  notes?:
    | T
    | {
        at?: T;
        user?: T;
        text?: T;
        id?: T;
      };
  sourceUrl?: T;
  sourceLocale?: T;
  ip?: T;
  userAgent?: T;
  consentAcceptedAt?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-groups_select".
 */
export interface ProductGroupsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  showOnFrontend?: T;
  order?: T;
  groupId?: T;
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
        noindex?: T;
        canonical?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  categoryId?: T;
  slug?: T;
  name?: T;
  description?: T;
  productGroup?: T;
  group?: T;
  parent?: T;
  cover?: T;
  icon?: T;
  order?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
        noindex?: T;
        canonical?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  productId?: T;
  sku?: T;
  model?: T;
  name?: T;
  slug?: T;
  productGroup?: T;
  images?:
    | T
    | {
        file?: T;
        id?: T;
      };
  description?: T;
  standards?:
    | T
    | {
        value?: T;
        id?: T;
      };
  sizeRange?:
    | T
    | {
        value?: T;
        id?: T;
      };
  materials?:
    | T
    | {
        value?: T;
        id?: T;
      };
  features?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  sellingPoints?:
    | T
    | {
        title?: T;
        text?: T;
        icon?: T;
        id?: T;
      };
  specifications?:
    | T
    | {
        label?: T;
        value?: T;
        group?: T;
        order?: T;
        id?: T;
      };
  sizeGuide?:
    | T
    | {
        title?: T;
        cornerLabel?: T;
        columns?:
          | T
          | {
              label?: T;
              id?: T;
            };
        rows?:
          | T
          | {
              label?: T;
              values?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  applications?:
    | T
    | {
        value?: T;
        id?: T;
      };
  scenarios?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  visualGroups?:
    | T
    | {
        variant?: T;
        title?: T;
        description?: T;
        images?:
          | T
          | {
              file?: T;
              id?: T;
            };
        id?: T;
      };
  certifications?:
    | T
    | {
        name?: T;
        issuer?: T;
        certNumber?: T;
        status?: T;
        validUntil?: T;
        attachment?: T;
        id?: T;
      };
  qualityEvidence?:
    | T
    | {
        type?: T;
        status?: T;
        title?: T;
        description?: T;
        attachment?: T;
        id?: T;
      };
  careInstructions?:
    | T
    | {
        value?: T;
        id?: T;
      };
  productFaqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  faqs?: T;
  video?: T;
  displayOrder?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solutions_select".
 */
export interface SolutionsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  cover?: T;
  order?: T;
  features?:
    | T
    | {
        value?: T;
        id?: T;
      };
  productTags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  content?: T;
  publishedAt?: T;
  solutionId?: T;
  slug?: T;
  relatedProductGroups?: T;
  relatedCategories?: T;
  relatedProducts?: T;
  isFeatured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  author?: T;
  cover?: T;
  featuredVideo?: T;
  category?: T;
  publishedAt?: T;
  featuredOrder?: T;
  isFeatured?: T;
  content?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  relatedNews?: T;
  relatedProducts?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  pageKey?: T;
  title?: T;
  slug?: T;
  hero?:
    | T
    | {
        enabled?: T;
        variant?: T;
        title?: T;
        subtitle?: T;
        backgroundImage?: T;
        backgroundVideo?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  blocks?:
    | T
    | {
        content?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        mediaText?:
          | T
          | {
              layout?: T;
              media?: T;
              title?: T;
              content?: T;
              ctaLabel?: T;
              ctaHref?: T;
              id?: T;
              blockName?: T;
            };
        productShowcase?:
          | T
          | {
              title?: T;
              category?: T;
              products?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        newsList?:
          | T
          | {
              title?: T;
              category?: T;
              news?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        faq?: T | FaqContentBlockSelect<T>;
        cta?:
          | T
          | {
              title?: T;
              description?: T;
              primaryLabel?: T;
              primaryHref?: T;
              secondaryLabel?: T;
              secondaryHref?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contact?:
          | T
          | {
              title?: T;
              showForm?: T;
              showMap?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
        noindex?: T;
        canonical?: T;
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqContentBlock_select".
 */
export interface FaqContentBlockSelect<T extends boolean = true> {
  title?: T;
  faqs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  scope?: T;
  pageRef?: T;
  productRef?: T;
  newsRef?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  order?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  folder?: T;
  usageCount?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        mobile?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search-logs_select".
 */
export interface SearchLogsSelect<T extends boolean = true> {
  eventType?: T;
  query?: T;
  locale?: T;
  hits?: T;
  resultId?: T;
  resultTitle?: T;
  resultType?: T;
  resultUrl?: T;
  userId?: T;
  ip?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  lastLoginAt?: T;
  twoFactorEnabled?: T;
  twoFactorSecret?: T;
  deletedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  permissions?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  user?: T;
  userEmail?: T;
  action?: T;
  collection?: T;
  documentId?: T;
  documentSnapshot?: T;
  ip?: T;
  userAgent?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  mainNav?:
    | {
        label: string;
        href: string;
        icon?: (number | null) | Media;
        target?: ('_self' | '_blank') | null;
        children?:
          | {
              label: string;
              href: string;
              icon?: (number | null) | Media;
              target?: ('_self' | '_blank') | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footerNav?:
    | {
        heading?: string | null;
        items?:
          | {
              label: string;
              href: string;
              icon?: (number | null) | Media;
              target?: ('_self' | '_blank') | null;
              children?:
                | {
                    label: string;
                    href: string;
                    icon?: (number | null) | Media;
                    target?: ('_self' | '_blank') | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  mobileNav?:
    | {
        label: string;
        href: string;
        icon?: (number | null) | Media;
        target?: ('_self' | '_blank') | null;
        children?:
          | {
              label: string;
              href: string;
              icon?: (number | null) | Media;
              target?: ('_self' | '_blank') | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  contact?: {
    phone?: string | null;
    email?: string | null;
    address?: string | null;
  };
  coordinates?: {
    lat?: number | null;
    lng?: number | null;
    zoom?: number | null;
  };
  socials?:
    | {
        platform: 'wechat' | 'weibo' | 'linkedin' | 'youtube' | 'facebook' | 'x' | 'other';
        url: string;
        icon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  siteName: string;
  tagline?: string | null;
  logo: {
    light: number | Media;
    dark: number | Media;
  };
  themeColor: string;
  defaultSeo?: {
    /**
     * 显示在浏览器标题和搜索结果标题里；不填时通常会使用页面名称。
     */
    title?: string | null;
    /**
     * 搜索结果里的摘要文案，建议控制在 200 字以内。
     */
    description?: string | null;
    /**
     * 用逗号分隔，建议 3-7 个。现在搜索引擎不强依赖它，填核心词即可。
     */
    keywords?: string | null;
    /**
     * 页面被分享到微信、社媒或聊天软件时，可能会作为预览图。
     */
    ogImage?: (number | null) | Media;
    /**
     * 一般不要开启。开启后，这个页面会尽量不出现在搜索结果里。
     */
    noindex?: boolean | null;
    /**
     * 用于告诉搜索引擎哪个地址是主版本；不懂可以留空。
     */
    canonical?: string | null;
  };
  mapServiceByLocale?:
    | {
        locale: 'zh' | 'en' | 'ru';
        service: 'amap' | 'google';
        id?: string | null;
      }[]
    | null;
  cookieConsent?: {
    enabled?: boolean | null;
    title?: string | null;
    description?: string | null;
    acceptLabel?: string | null;
    rejectLabel?: string | null;
    essentialOnlyLabel?: string | null;
  };
  analytics?: {
    enabled?: boolean | null;
    /**
     * 仅保存公开 websiteId；不要填写 API Key。
     */
    umamiWebsiteId?: string | null;
  };
  icp: string;
  /**
   * [NEEDS-INPUT] 格式：湘公网安备 XXXXXXXXXXXXX号。
   */
  publicSecurityRecord?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  mainNav?:
    | T
    | {
        label?: T;
        href?: T;
        icon?: T;
        target?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              icon?: T;
              target?: T;
              id?: T;
            };
        id?: T;
      };
  footerNav?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              label?: T;
              href?: T;
              icon?: T;
              target?: T;
              children?:
                | T
                | {
                    label?: T;
                    href?: T;
                    icon?: T;
                    target?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  mobileNav?:
    | T
    | {
        label?: T;
        href?: T;
        icon?: T;
        target?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              icon?: T;
              target?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  contact?:
    | T
    | {
        phone?: T;
        email?: T;
        address?: T;
      };
  coordinates?:
    | T
    | {
        lat?: T;
        lng?: T;
        zoom?: T;
      };
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        icon?: T;
        id?: T;
      };
  siteName?: T;
  tagline?: T;
  logo?:
    | T
    | {
        light?: T;
        dark?: T;
      };
  themeColor?: T;
  defaultSeo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
        noindex?: T;
        canonical?: T;
      };
  mapServiceByLocale?:
    | T
    | {
        locale?: T;
        service?: T;
        id?: T;
      };
  cookieConsent?:
    | T
    | {
        enabled?: T;
        title?: T;
        description?: T;
        acceptLabel?: T;
        rejectLabel?: T;
        essentialOnlyLabel?: T;
      };
  analytics?:
    | T
    | {
        enabled?: T;
        umamiWebsiteId?: T;
      };
  icp?: T;
  publicSecurityRecord?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}
